POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username": "jason",
    "email": "ko@abc.com",
    "password": "1232131232"
}


PUT http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "jason",
    "email": "ko@abc.com",
    "password": "1232131232"
}